spring:
  application:
    name: account-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/banking_accounts
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: account-service
      auto-offset-reset: earliest

server:
  port: 8082

account:
  checking:
    maintenance-fee: 10.00
  savings:
    monthly-movement-limit: 5
  opening:
    minimum-amount: 0
  transactions:
    free-monthly: 5
    commission-fee: 2.50
  vip:
    min-daily-average: 500.00
  pyme:
    maintenance-fee: 0

services:
  customer:
    base-url: http://localhost:8081
  credit:
    base-url: http://localhost:8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: ${EUREKA_ENABLED:true}
